### ISSUE TITLE
why no cutekit ?

### ISSUE THREAD

**Issue by keyboard-slayer** [cute-engineering/cuteworkstation#1]
Title is self-explanatory ( if you want I can do a PR for u :3 )

**Comment by d0p1s4m4** [comment]
There are many reasons for this, and I'll try to list them.

The first are technical:
- GNU autotools support multiple operating systems and are fairly easy to use (even under Windows from M$, which is part of the Tier 1).
- Cutekit lacks system and environment checks (e.g. whether x or y headers exist, whether x or y tools exist and support x or y features).
- Cutekit does not integrate with GNU Gettext and other GNU tools.
- GNU Autotools are easier to integrate with RPM,deb packaging tools.

The next are personal:
- I'm more familiar with GNU Autotools :') 
- I'm in love with GNU Autotools. UwU
